set(wholeBodyInterface_TAG new_wbi_ID)
set(yarpWholeBodyInterface_TAG new_wbi_ID)
set(codyco-modules_TAG new_wbi_ID)
set(codycoCommons_TAG new_wbi_ID)
set(iDynTree_TAG new_wbi_ID)
set(motorFrictionIdentificationLib_TAG new_wbi_ID)
set(WBIToolbox_TAG new_wbi_ID)
set(mexWholeBodyModel_TAG new_wbi_ID)
