set(wholeBodyInterface_TAG v0.1)
set(yarpWholeBodyInterface_TAG v0.1)
set(codyco-modules_TAG v0.1)
set(codycoCommons_TAG v0.1)
set(iDynTree_TAG v0.1)
set(motorFrictionIdentificationLib_TAG v0.1)
set(WBIToolbox_TAG v0.1)
set(mexWholeBodyModel_TAG v0.1)
